name: fitness_recommendation
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.1        # Để lấy path lưu database
  path: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  drift_dev: ^2.28.1